rm -rf build
mkdir build
cd build
cmake -G"Visual Studio 14 2015" -DBUILD_BLACKHART_SAMPLES:BOOL=true -DGLFW_AUTO_COMPILE:BOOL=true -DGLFW_BUILD_DOCS:BOOL=false -DGLFW_BUILD_EXAMPLES:BOOL=false -DGLFW_BUILD_TESTS:BOOL=false -DGLFW_INSTALL:BOOL=false -L ..
cd ..